version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output/data --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/data/input.feather

  preprocess_inputs:
    run: python:latest python analysis/preprocess_inputs.py --output-format feather
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        cohort_with_duration: output/data/input_processed.feather
