version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2015-03-01 to 2022-02-01 by month" --output-dir=output/data --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/data/input_2*.feather

  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-dir=output/data --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/data/input_ethnicity.feather

  join_ethnicity_all_patients:
    run: python:latest python analysis/join_ethnicity.py --output-dir=output/data --output-format feather
    needs: [generate_study_population, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/data/input_20*.feather