version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_2015:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2015-01-01" --output-dir=output/data --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/data/input_2015-01-01.feather

  generate_study_population_2016:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2016-01-01" --output-dir=output/data --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/data/input_2016-01-01.feather

  generate_study_population_2017:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2017-01-01" --output-dir=output/data --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/data/input_2017-01-01.feather

  generate_study_population_2018:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2018-01-01" --output-dir=output/data --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/data/input_2018-01-01.feather

  generate_study_population_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-01-01" --output-dir=output/data --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/data/input_2019-01-01.feather

  generate_study_population_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-01-01" --output-dir=output/data --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/data/input_2020-01-01.feather

  generate_study_population_2021:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-01-01" --output-dir=output/data --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/data/input_2021-01-01.feather

  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-dir=output/data --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/data/input_ethnicity.feather

  join_ethnicity_all_patients:
    run: python:latest python analysis/join_ethnicity.py --output-dir=output/data --output-format feather
    needs: [generate_study_population_2015, generate_study_population_2016, generate_study_population_2017, generate_study_population_2018, generate_study_population_2019, generate_study_population_2020, generate_study_population_2021, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/data/input_20*.feather